config/routes.rb
Rails.application.routes.draw do

  root 'batches#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'schools#index'
  namespace :admin do
    resources :schools
    resources :school_admins
    resources :users
    resources :courses
    resources :batches
    resources :enrolment_requests do
      patch :approve, on: :member
      patch :reject, on: :member
    end
  end

  resources :enrolments
  resources :batches, only: [:index] do
    collection do
      get 'current_user_batches', as: 'current'
    end
    member do
      get 'show_users'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post 'login', to: 'sessions#create'
        delete 'logout', to: 'sessions#destroy'
      end


    end
  end
end

app/models/enrolment_request.rb
class EnrolmentRequest < ApplicationRecord
  enum status: %i[pending approved rejected]

  belongs_to :student, class_name: 'User'
  belongs_to :batch
end

app/controllers/admin/enrolment_requests_controller.rb
class Admin::EnrolmentRequestsController < Admin::BaseController
  before_action :set_enrolment_request, only: %i[ show edit update destroy approve reject ]

  # GET /enrolment_requests or /enrolment_requests.json
  def index
    if current_user.admin?
      @enrolment_requests = EnrolmentRequest.all
    else
      @enrolment_requests = EnrolmentRequest.joins(batch: { course: :school })
                                        .where(schools: { id: current_user.schools.pluck(:id) })
    end
  end

  # GET /enrolment_requests/1 or /enrolment_requests/1.json
  def show
  end

  # GET /enrolment_requests/new
  def new
    @enrolment_request = EnrolmentRequest.new
  end

  # GET /enrolment_requests/1/edit
  def edit
  end

  # POST /enrolment_requests or /enrolment_requests.json
  def create
    @enrolment_request = EnrolmentRequest.new(enrolment_request_params)

    respond_to do |format|
      if @enrolment_request.save
        format.html { redirect_to admin_enrolment_request_url(@enrolment_request), notice: "Enrolment request was successfully created." }
        format.json { render :show, status: :created, location: @enrolment_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrolment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolment_requests/1 or /enrolment_requests/1.json
  def update
    respond_to do |format|
      if @enrolment_request.update(enrolment_request_params)
        format.html { redirect_to admin_enrolment_request_url(@enrolment_request), notice: "Enrolment request was successfully updated." }
        format.json { render :show, status: :ok, location: @enrolment_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrolment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolment_requests/1 or /enrolment_requests/1.json
  def destroy
    @enrolment_request.destroy

    respond_to do |format|
      format.html { redirect_to admin_enrolment_requests_url, notice: "Enrolment request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve
    @enrolment_request.update(status: "approved")
    redirect_to admin_enrolment_requests_path, notice: "Enrolment request approved."
  end

  def reject
    @enrolment_request.update(status: "rejected")
    redirect_to admin_enrolment_requests_path, notice: "Enrolment request rejected."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment_request
      @enrolment_request = EnrolmentRequest.find(params[:id])
      if current_user.admin?
        @batches = Batch.all
      else
        @batches = Batch.joins(:course => :school)
        .where(:schools => {:id => current_user.schools.pluck(:id)})
      end
    end

    # Only allow a list of trusted parameters through.
    def enrolment_request_params
      params.require(:enrolment_request).permit(:batch_id, :student_id, :status)
    end
end

app/helpers/enrolment_requests_helper.rb
module EnrolmentRequestsHelper
end

app/views/admin/enrolment_requests/_form.html.erb
<%= form_with(model: [:admin, enrolment_request], local: true) do |form| %>
  <% if enrolment_request.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(enrolment_request.errors.count, "error") %> prohibited this enrolment_request from being saved:</h4>

      <ul>
        <% enrolment_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :batch_id %>
    <% if current_user.schooladmin? %>
      <%= form.collection_select :batch_id, Batch.joins(:course => :school)
        .where(:schools => {:id => current_user.schools.pluck(:id)}), :id, :name, {}, class: "form-control" %>
    <% else %>
      <%= form.collection_select :batch_id, Batch.all, :id, :name, {}, class: "form-control" %>
    <% end %>
  </div>


  <div class="form-group">
    <%= form.label :student_id %>
    <%= form.collection_select :student_id, User.all, :id, ->(user) { "#{user.name} (#{user.email})" }, {}, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, EnrolmentRequest.statuses.keys.to_a, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/enrolment_requests/edit.html.erb
<h1>Editing Enrolment Request</h1>

<%= render 'form', enrolment_request: @enrolment_request %>

<%= link_to 'Show', admin_enrolment_requests_path(@enrolment_request) %> |
<%= link_to 'Back', admin_enrolment_requests_path %>

app/views/admin/enrolment_requests/index.html.erb
<h1>Enrollment Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Batch</th>
      <th>Student</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolment_requests.each do |enrolment_request| %>
      <tr>
        <td><%= enrolment_request.batch.name.capitalize %></td>
        <td><%= enrolment_request.student.email %></td>
        <td><%= enrolment_request.status.upcase %></td>
        <td><%= link_to 'Show', admin_enrolment_requests_path(enrolment_request), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_admin_enrolment_request_path(enrolment_request), class: "btn btn-secondary" %></td>
        <%
=begin%>
  This destroy method is not needed here.
<%
=end%>
        <%#= link_to 'Destroy', [:admin, enrolment_request], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %> 
      
        <td><%= link_to 'Approve', approve_admin_enrolment_request_path(enrolment_request), method: :patch, class: "btn btn-success" %></td>
        <td><%= link_to 'Reject', reject_admin_enrolment_request_path(enrolment_request), method: :patch, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Enrolment Request', new_admin_enrolment_request_path, class: "btn btn-success" %>

app/views/admin/enrolment_requests/new.html.erb
<h1>New Enrolment Request</h1>

<%= render 'form', enrolment_request: @enrolment_request %>

<%= link_to 'Back', admin_enrolment_requests_path %>

app/views/admin/enrolment_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @enrolment_request.batch_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @enrolment_request.student_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @enrolment_request.status %>
</p>

<%= link_to 'Edit', edit_admin_enrolment_request_path(@enrolment_request) %> |
<%= link_to 'Back', admin_enrolment_requests_path %>