config/routes.rb
Rails.application.routes.draw do

  root 'batches#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'schools#index'
  namespace :admin do
    resources :schools
    resources :school_admins
    resources :users
    resources :courses
    resources :batches
    resources :enrolment_requests do
      patch :approve, on: :member
      patch :reject, on: :member
    end
  end

  resources :enrolments
  resources :batches, only: [:index] do
    collection do
      get 'current_user_batches', as: 'current'
    end
    member do
      get 'show_users'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post 'login', to: 'sessions#create'
        delete 'logout', to: 'sessions#destroy'
      end


    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = Role::ROLES

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enrolment_requests, foreign_key: :student_id
  has_many :batches, through: :enrolment_requests
  has_many :school_admins
  has_many :schools, through: :school_admins

  belongs_to :role, optional: true

  scope :by_role, -> (role_name) { joins(:role).where(roles: { name: role_name }) }

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :phone_number, format: { with: /\A[0-9]{10}\z/, message: "must be a 10-digit number" }, allow_blank: true

  ROLES.each do |role|
    define_method("#{role.downcase}?") do
      self.role&.name == role
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :authorize!
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :phone_number, :email, :password, :role_id)
    end

    def authorize!
      unless current_user_can?("school_admins_create")
        redirect_to root_path, alert: "You are not authorized to access this page."
      end
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def index
    @users = User.all
    render json: @users, each_serializer: UserSerializer
  end

  def show
    @user = User.find(params[:id])
    render json: @user, serializer: UserSerializer
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, serializer: UserSerializer, status: :created
    else
      render json: { errors: @user.errors }, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      render json: @user, serializer: UserSerializer
    else
      render json: { errors: @user.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    head :no_content
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true, class: "form") do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "control-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number, class: "control-label" %>
    <%= form.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, class: "control-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <% if form.object.new_record? %>
    <div class="form-group">
      <%= form.label :password, class: "control-label" %>
      <%= form.text_field :password, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :role_id, class: "control-label" %>
    <%= form.collection_select :role_id, Role.all, :id, :name, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', admin_users_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <h1>Users</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Phone number</th>
            <th>Email</th>
            <th>Role</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.phone_number %></td>
              <td><%= user.email %></td>
              <td><%= user.role.name %></td>
              <td><%= link_to 'Show', admin_user_path(user), class: 'btn btn-primary' %></td>
              <td><%= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-secondary' %></td>
              <td><%= link_to 'Destroy', [:admin,user], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= link_to 'New User', new_admin_user_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          User Details
        </div>
        <div class="card-body">
          <p class="card-text">
            <strong>Name:</strong> <%= @user.name %>
          </p>
          <p class="card-text">
            <strong>Phone number:</strong> <%= @user.phone_number %>
          </p>
          <p class="card-text">
            <strong>Email:</strong> <%= @user.email %>
          </p>
          <p class="card-text">
            <strong>Role:</strong> <%= @user.role.name %>
          </p>
          <%= link_to 'Edit', edit_admin_user_path(@user), class: "btn btn-primary" %>
          <%= link_to 'Back', admin_users_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>