config/routes.rb
Rails.application.routes.draw do

  root 'batches#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'schools#index'
  namespace :admin do
    resources :schools
    resources :school_admins
    resources :users
    resources :courses
    resources :batches
    resources :enrolment_requests do
      patch :approve, on: :member
      patch :reject, on: :member
    end
  end

  resources :enrolments
  resources :batches, only: [:index] do
    collection do
      get 'current_user_batches', as: 'current'
    end
    member do
      get 'show_users'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post 'login', to: 'sessions#create'
        delete 'logout', to: 'sessions#destroy'
      end


    end
  end
end

app/models/school_admin.rb
class SchoolAdmin < ApplicationRecord
  belongs_to :user
  belongs_to :school

  validates :user_id, uniqueness: { scope: :school_id }
  validate :check_user_role

  def check_user_role
    unless user && user.role == Role::SCHOOL_ADMIN
      errors.add(:user, 'must have the role of school admin')
    end
  end
end

app/controllers/admin/school_admins_controller.rb
class Admin::SchoolAdminsController < Admin::BaseController
  before_action :authorize!
  before_action :set_school_admin, only: %i[ show edit update destroy ]

  # GET /school_admins or /school_admins.json
  def index
    @school_admins = SchoolAdmin.all
  end

  # GET /school_admins/1 or /school_admins/1.json
  def show
  end

  # GET /school_admins/new
  def new
    @school_admin = SchoolAdmin.new
  end

  # GET /school_admins/1/edit
  def edit
  end

  # POST /school_admins or /school_admins.json
  def create
    @school_admin = SchoolAdmin.new(school_admin_params)

    respond_to do |format|
      if @school_admin.save
        format.html { redirect_to admin_school_admin_url(@school_admin), notice: "School admin was successfully created." }
        format.json { render :show, status: :created, location: @school_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_admins/1 or /school_admins/1.json
  def update
    respond_to do |format|
      if @school_admin.update(school_admin_params)
        format.html { redirect_to admin_school_admin_url(@school_admin), notice: "School admin was successfully updated." }
        format.json { render :show, status: :ok, location: @school_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_admins/1 or /school_admins/1.json
  def destroy
    @school_admin.destroy

    respond_to do |format|
      format.html { redirect_to admin_school_admins_url, notice: "School admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_admin
      @school_admin = SchoolAdmin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_admin_params
      params.require(:school_admin).permit(:user_id, :school_id)
    end

    def authorize!
      unless current_user_can?("school_admins_create")
        redirect_to root_path, alert: "You are not authorized to access this page."
      end
    end
end

app/helpers/school_admins_helper.rb
module SchoolAdminsHelper
end

app/views/admin/school_admins/_form.html.erb
<%= form_with(model: [:admin, school_admin], local: true, class: "form") do |form| %>
  <% if school_admin.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(school_admin.errors.count, "error") %> prohibited this school_admin from being saved:</h2>

      <ul>
        <% school_admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.by_role(Role::SCHOOL_ADMIN), :id, ->(user) { "#{user.name} (#{user.email})" }, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :school_id %>
    <%= form.collection_select :school_id, School.all, :id, :name, {}, { class: "form-control" } %>
  </div>

  <div class="form-actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/school_admins/edit.html.erb
<h1>Editing School Admin</h1>

<%= render 'form', school_admin: @school_admin %>

<%= link_to 'Show', admin_school_path(@school_admin) %> |
<%= link_to 'Back', admin_school_admins_path %>

app/views/admin/school_admins/index.html.erb
<h1>School Admins</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_admins.each do |school_admin| %>
      <tr>
        <td><%= school_admin.user.email %></td>
        <td><%= school_admin.school.name %></td>
        <td><%= link_to 'Show', admin_school_admin_path(school_admin), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Edit', edit_admin_school_admin_path(school_admin), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', [:admin, school_admin], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user_can?('schools_create')%>
  <%= link_to 'New School Admin', new_admin_school_admin_path, class: "btn btn-primary" %>
<% end %>

app/views/admin/school_admins/new.html.erb
<h1>New School Admin</h1>

<%= render 'form', school_admin: @school_admin %>

<%= link_to 'Back', admin_school_admins_path %>

app/views/admin/school_admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @school_admin.user.email %>
</p>

<p>
  <strong>School:</strong>
  <%= @school_admin.school.name %>
</p>

<%= link_to 'Edit', edit_admin_school_admin_path(@school_admin) %> |
<%= link_to 'Back', admin_school_admins_path %>