config/routes.rb
Rails.application.routes.draw do

  root 'batches#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'schools#index'
  namespace :admin do
    resources :schools
    resources :school_admins
    resources :users
    resources :courses
    resources :batches
    resources :enrolment_requests do
      patch :approve, on: :member
      patch :reject, on: :member
    end
  end

  resources :enrolments
  resources :batches, only: [:index] do
    collection do
      get 'current_user_batches', as: 'current'
    end
    member do
      get 'show_users'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      devise_scope :user do
        post 'login', to: 'sessions#create'
        delete 'logout', to: 'sessions#destroy'
      end


    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :course
  has_many :enrolment_requests
  has_many :users, through: :enrolment_requests, source: :student

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :course, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school
  has_many :batches, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 1000 }

end

app/models/enrolment_request.rb
class EnrolmentRequest < ApplicationRecord
  enum status: %i[pending approved rejected]

  belongs_to :student, class_name: 'User'
  belongs_to :batch
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_permissions
  has_many :roles, through: :role_permissions
end

app/models/role.rb
class Role < ApplicationRecord
  ADMIN = 'Admin'.freeze
  SCHOOL_ADMIN = 'SchoolAdmin'.freeze
  STUDENT = 'Student'.freeze

  ROLES = [ADMIN, SCHOOL_ADMIN, STUDENT].freeze

  has_many :users
  has_many :role_permissions
  has_many :permissions, through: :role_permissions

  validates :name, inclusion: { in: ROLES, message: "must be one of #{ROLES.join(', ')}" }

  def permission?(permission_name)
    permissions.exists?(name: permission_name)
  end
end

app/models/role_permission.rb
class RolePermission < ApplicationRecord
  belongs_to :role
  belongs_to :permission
end

app/models/school.rb
class School < ApplicationRecord
  has_many :courses
  has_many :school_admins

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :contact_details, presence: true
end

app/models/school_admin.rb
class SchoolAdmin < ApplicationRecord
  belongs_to :user
  belongs_to :school

  validates :user_id, uniqueness: { scope: :school_id }
  validate :check_user_role

  def check_user_role
    unless user && user.role == Role::SCHOOL_ADMIN
      errors.add(:user, 'must have the role of school admin')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = Role::ROLES

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enrolment_requests, foreign_key: :student_id
  has_many :batches, through: :enrolment_requests
  has_many :school_admins
  has_many :schools, through: :school_admins

  belongs_to :role, optional: true

  scope :by_role, -> (role_name) { joins(:role).where(roles: { name: role_name }) }

  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :phone_number, format: { with: /\A[0-9]{10}\z/, message: "must be a 10-digit number" }, allow_blank: true

  ROLES.each do |role|
    define_method("#{role.downcase}?") do
      self.role&.name == role
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
    @batches = Batch.left_joins(:enrolment_requests)
                   .where(enrolment_requests: { id: nil })
                   .where('start_date > ?', Date.today)
  end

  def current_user_batches
    @batches = current_user.enrolment_requests.includes(:batch).map(&:batch)
  end

  def show_users
    @batch = Batch.find(params[:id])
    @users = @batch.users.where.not(id: current_user.id)
  end
end

app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  def create
    result = ::EnrolmentService.create_enrollment(params[:batch_id], current_user.id)
    if result[:success]
      flash[:success] = result[:message]
    else
      flash[:error] = result[:message]
    end
    redirect_to batches_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
require 'json_web_token'
module AuthenticationHelper

  def logged_in?
    current_user.present?
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:error] = "You must be an admin to access this section"
      redirect_to root_path
    end
  end

  def require_school_admin
    unless logged_in? && (current_user.admin? || current_user.schooladmin?)
      flash[:error] = "You must be a school admin to access this section"
      redirect_to root_path
    end
  end

  def current_user_can?(permission_name)
    current_user&.role&.permission?(permission_name)
  end

  def require_permission(permission_name)
    unless current_user_can?(permission_name)
      flash[:error] = "You do not have permission to perform this action"
      redirect_to root_path
    end
  end

  def authenticate_request!
    unless user_id_in_token?
      render json: { error: 'Not Authorized' }, status: :unauthorized
      return
    end
    byebug
    @current_user = User.find(auth_token["user_id"])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { error: 'Not Authorized' }, status: :unauthorized
  end

  def auth_token
    @auth_token ||= ::JsonWebToken.decode(request.headers['Authorization'].split(' ').last)
  end

  def user_id_in_token?
    request.headers['Authorization'].present? && auth_token && auth_token[:user_id].to_i
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

app/helpers/school_admins_helper.rb
module SchoolAdminsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">ELearning</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= current_page?(root_path) ? 'active' : '' %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item <%= current_page?(current_batches_path) ? 'active' : '' %>">
          <%= link_to "My Batches", current_batches_path, class: "nav-link" %>
        </li>
        <% if current_user.admin? || current_user.schooladmin? %>
          <li class="nav-item <%= current_page?(admin_enrolment_requests_path) ? 'active' : '' %>">
            <%= link_to "Admin", admin_enrolment_requests_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <span class="navbar-text">Signed in as <%= current_user.email %></span>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearning Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">ELearning Dashboard</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item <%= current_page?(admin_schools_path) ? 'active' : '' %>">
              <%= link_to 'Schools', admin_schools_path, class: 'nav-link' %>
            </li>
            <% if current_user.admin? %>
            <li class="nav-item <%= current_page?(admin_users_path) ? 'active' : '' %>">
              <%= link_to 'Users', admin_users_path, class: 'nav-link' %>
            </li>
            <%end%>
            <% if current_user.admin? %>
            <li class="nav-item <%= current_page?(admin_school_admins_path) ? 'active' : '' %>">
              <%= link_to 'SchoolAdmins', admin_school_admins_path, class: 'nav-link' %>
            </li>
            <%end%>
            <li class="nav-item <%= current_page?(admin_batches_path) ? 'active' : '' %>">
              <%= link_to 'Batches', admin_batches_path, class: 'nav-link' %>
            </li>

            <li class="nav-item <%= current_page?(admin_courses_path) ? 'active' : '' %>">
              <%= link_to 'Courses', admin_courses_path, class: 'nav-link' %>
            </li>
            
            <li class="nav-item <%= current_page?(admin_enrolment_requests_path) ? 'active' : '' %>">
              <%= link_to 'Enrollment Requests', admin_enrolment_requests_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <span class="navbar-text">Signed in as <%= current_user.email %></span>
              </li>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Content -->
    <div class="container mt-4">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>

    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js', 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdLearn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js', 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js', 'application' %> 
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-4">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>